server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
        namespace: public
    gateway:
      enabled: false

logging:
  level:
    com.minigithub: DEBUG
