server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: blog-service-route
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848

jwt:
  secret: ${JWT_SECRET}
db:
  password: ${DB_PASSWORD:root}

logging:
  level:
    com.minigithub: DEBUG
